export const categories = [
    "Hot & Cold Sandwiches",
    "Street Food",
    "Mishti Milkshakes",
    "Cold Drinks",
    "Ice Coffee",
    "Tea & Coffee",
    "Weekly Specials"
];

export const allItems = [
    {
        title: "Cheese & Tomato Baguette",
        price: "£3.50",
        category: "Hot & Cold Sandwiches",
        image: "/g6.jpg",
    },
    {
        title: "Tuna mayo cob",
        price: "£2.00",
        category: "Hot & Cold Sandwiches",
        image: "/g112.webp",
    },
    {
        title: "Chicken Baguette",
        price: "£3.50",
        category: "Hot & Cold Sandwiches",
        image: "/g16.jpg",
    },
    {
        title: "Tuna Baguette",
        price: "£3.50",
        category: "Hot & Cold Sandwiches",
        image: "/g112.jpg",
    },
    {
        title: "Chilli Cheese Toastie",
        price: "£2.50",
        category: "Hot & Cold Sandwiches",
        image: "/g18.jpg",
    },
    {
        title: "Mushroom & Cheese toastie",
        price: "£3.35",
        category: "Hot & Cold Sandwiches",
        image: "/g112.webp",
    },
    {
        title: "Double Cheese Baget",
        price: "£2.00",
        category: "Hot & Cold Sandwiches",
        image: "/g112.webp",
    },
    {
        title: "Cheese & Tomato Baget",
        price: "£2.25",
        category: "Hot & Cold Sandwiches",
        image: "/g12.webp",
    },
    {
        title: "Samosas (veg/pot)",
        price: "£1.00",
        category: "Street Food",
        image: "/g18.jpg",
    },
    {
        title: "Samosas (chicken/meat)",
        price: "£1.50",
        category: "Street Food",
        image: "/g18.jpg",
    },
    {
        title: "Jaal muri",
        price: "£2.50",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Mishti Phan",
        price: "£1.00",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Jaal muri",
        price: "£2.50",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Pani Puri Fruit bombs (6pcs)",
        price: "£5.00",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Spicy chana chatt",
        price: "£3.50",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Samosa Chatt",
        price: "£5.00",
        category: "Street Food",
        image: "/g3.jpg",
    },
    {
        title: "Masala Omelette Parata",
        price: "£3.00",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Hash brown cob",
        price: "£1.50",
        category: "Street Food",
        image: "/g7.jpg",
    },

    {
        title: "Masala Omlette",
        price: "£2.00",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Muglai Parata**",
        price: "£3.95 / £7",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Chicken & Spinach pasty**",
        price: "£3.50",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Chicken kebab bap**",
        price: "£3.50",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Croissant butter",
        price: "£1.50",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Almond Croissant",
        price: "£2.00",
        category: "Street Food",
        image: "/g7.jpg",
    },
    {
        title: "Choc’n’nut Granola Bowl",
        price: "£3.49",
        category: "Street Food",
        image: "/g14.png",
    },
    {
        title: "Fruit ’n’nut Granola Bowl",
        price: "£3.49",
        category: "Street Food",
        image: "/g10.png",
    },
    {
        title: "Home baked",
        price: "£2.50",
        category: "Street Food",
        image: "/g18.jpg",
    },

    {
        title: "Gulap Jam Milkshake",
        price: "£3.50",
        category: "Mishti Milkshakes",
        image: "/g0.png",
    },
    {
        title: "Kala Jam Milkshake",
        price: "£3.50",
        category: "Mishti Milkshakes",
        image: "/g0.png",
    },
    {
        title: "House Special Milkshake",
        price: "£4.00",
        desc: "Pistachio & salted caramel",
        category: "Mishti Milkshakes",
        image: "/g0.png",
    },
    {
        title: "Mango Lassi",
        price: "£3.50",
        category: "Cold Drinks",
        image: "/g13.png",
    },
    {
        title: "Brazilian Lemonade",
        price: "£3.95",
        category: "Cold Drinks",
        image: "/g4.jpg",
    },
    {
        title: "Strawberry Lemonade",
        price: "£3.95",
        category: "Cold Drinks",
        image: "/g8.jpg",
    },

    {
        title: "House Ice Coffee",
        price: "£3 (small) / £3.95 (large)",
        category: "Ice Coffee",
        image: "/g2.jpg",
    },
    {
        title: "Caramel Ice Coffee",
        price: "£3 / £3.95",
        category: "Ice Coffee",
        image: "/g0.png",
    },

    {
        title: "Rice Pudding",
        price: "£4.95",
        category: "Weekly Specials",
        image: "/g0.png",
    },
    {
        title: "Fruit Salad",
        price: "£4.95",
        category: "Weekly Specials",
        image: "/s1.png",
    },
    {
        title: "Coconut Crepes",
        price: "£3.50",
        category: "Weekly Specials",
        image: "/g0.png",
    },

    {
        title: "Chai (House Special)",
        price: "£2.00",
        category: "Tea & Coffee",
        image: "/g20.png",
    },
    {
        title: "Double Choc House Mocha",
        price: "£2.40",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Pink Chai",
        price: "£2.20",
        category: "Tea & Coffee",
        image: "/g1.jpg",
    },
    {
        title: "Caramel Chai",
        price: "£2.20",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Moroccan Tea",
        price: "£2.75",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "English Tea",
        price: "£1.75",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Herbal Blue Tea",
        price: "£4.19",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Mango Flower Tea",
        price: "£4.19",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Karak Coffee (House Special)",
        price: "£2.00",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Chai Latte",
        price: "£2.20",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Espresso",
        price: "£1.50",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Black Coffee / Flat White",
        price: "£2.85",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Cappuccino",
        price: "£2.85",
        category: "Tea & Coffee",
        image: "/g0.png",
    },
    {
        title: "Hot Chocolate",
        price: "£2.00",
        category: "Tea & Coffee",
        image: "/g0.png",
    },

];
