export const categories = [
    "Hot & Cold Sandwiches",
    "Street Food",
    "Mishti Milkshakes",
    "Cold Drinks",
    "Ice Coffee",
    "100% Fresh Juice",
    "Tea & Coffee",
];

export const allItems = [
    //Hot & Cold Sandwiches
    {
        title: "Cheese Salad Baguette",
        price: "£3.50",
        category: "Hot & Cold Sandwiches",
        image: "/g6.jpg",
    },
    {
        title: "Chicken Baguette",
        price: "£3.50",
        category: "Hot & Cold Sandwiches",
        image: "/Chicken.png",
    },
    {
        title: "Tuna Baguette",
        price: "£3.50",
        category: "Hot & Cold Sandwiches",
        image: "/Tuna Baguette.png",
    },
    {
        title: "Tuna Cob",
        price: "£2.00",
        category: "Hot & Cold Sandwiches",
        image: "/Tuna cob.png",
    },
    {
        title: "Chicken Cob",
        price: "£2.00",
        category: "Hot & Cold Sandwiches",
        image: "/Chicken cob.png",
    },
    {
        title: "Chilli Cheese Toastie",
        price: "£2.50",
        category: "Hot & Cold Sandwiches",
        image: "/g18.jpg",
    },
    {
        title: "Pepperoni & Cheese Toasty",
        price: "£3.50",
        category: "Hot & Cold Sandwiches",
        image: "/Pepperoni and Cheese.png",
    },
    {
        title: " Pepperoni & Cheese Bagel",
        price: "£3.00",
        category: "Hot & Cold Sandwiches",
        image: "/Pepperoni.png",
    },
    {
        title: "Double Cheese Bagel",
        price: "£2.00",
        category: "Hot & Cold Sandwiches",
        image: "/Double Cheese Bagel.png",
    },
    {
        title: "Cheese & Tomato Baget",
        price: "£2.25",
        category: "Hot & Cold Sandwiches",
        image: "/g12.webp",
    },
    {
        title: "Sausage and Hash brown Baguette",
        price: "£3.50",
        category: "Hot & Cold Sandwiches",
        image: "/Sausage.png",
    },
    {
        title: "Salmon Bagel",
        price: "£3.50",
        category: "Hot & Cold Sandwiches",
        image: "/Salmon.png",
    },

    //Street Food
    {
        title: "Samosas (Mixed Veg)",
        price: "£1.00",
        category: "Street Food",
        image: "/Samosas.png",
    },
    {
        title: "Samosas (Chicken)",
        price: "£1.50",
        category: "Street Food",
        image: "/Samosas.png",
    },
    {
        title: "Samosa Chatt",
        price: "£5.00",
        category: "Street Food",
        image: "/g3.jpg",
    },
    {
        title: "Spicy chana chatt",
        price: "£3.50",
        category: "Street Food",
        image: "/spicy channa chaat.png",
    },
    {
        title: "Chicken Kebab Bap",
        price: "£4.00",
        category: "Street Food",
        image: "/Chicken Kebab Bap.png",
    },
    {
        title: "Chicken & Spinach Pasty",
        price: "£3.50",
        category: "Street Food",
        image: "/Chicken & Spinach Pasty.png",
    },
    {
        title: "Hashbrown Cob",
        price: "£1.50",
        category: "Street Food",
        image: "/hashbrown.png",
    },
    {
        title: "Masala Omelette Parata",
        price: "£3.00",
        category: "Street Food",
        image: "/masala.png",
    },
    {
        title: "Butter Parata",
        price: "£1.20",
        category: "Street Food",
        image: "/Butter Parata.png",
    },
    {
        title: "Masala Omelette",
        price: "£2.00",
        category: "Street Food",
        image: "/masala.png",
    },
    {
        title: "Double Omelette Parata",
        price: "£4.00",
        category: "Street Food",
        image: "/Double Omelette Parata.png",
    },
    {
        title: "Desi Breakfast",
        price: "£7.50",
        category: "Street Food",
        image: "/masala.png",
    },
    {
        title: "FullyLoaded Breakfast Wrap",
        price: "£4.50",
        category: "Street Food",
        image: "/FullyLoaded Breakfast Wrap.png",
    },
    {
        title: "Sheesh Kebab Parata Roll",
        price: "£3.00",
        category: "Street Food",
        image: "/Sheesh Kebab Parata Roll.png",
    },
    {
        title: "Sheesh Kebab Egg Roll",
        price: "£4.50",
        category: "Street Food",
        image: "/Sheesh Kebab Egg Roll.jpeg",
    },
    {
        title: "Double Sheesh Kebab Pita",
        price: "£6.00",
        category: "Street Food",
        image: "/Double Sheesh Kebab Pita.png",
    },
    {
        title: "Fruit ’n’nut Granola Bowl",
        price: "£3.49",
        category: "Street Food",
        image: "/Fruit n nut.png",
    },
    {
        title: "Choc’n’nut Granola Bowl",
        price: "£2.00",
        category: "Street Food",
        image: "/choc.png",
    },
    {
        title: "Masala Wedges",
        price: "£2.50",
        category: "Street Food",
        image: "/Masala Wedges.png",
    },
    {
        title: "Butter Croissant",
        price: "£1.50",
        category: "Street Food",
        image: "/croissant.png",
    },
    {
        title: "Almond/Choc Croissant",
        price: "£2.50",
        category: "Street Food",
        image: "/AlmondChoc Croissant.png",
    },
    {
        title: "Chocolate Croissant",
        price: "£2.00",
        category: "Street Food",
        image: "/Chocolate.png",
    },
    {
        title: "White Chocolate Cookie",
        price: "£2.00",
        category: "Street Food",
        image: "/White.png",
    },
    {
        title: "Chocolate Chip Cookie",
        price: "£2.00",
        category: "Street Food",
        image: "/Chocolate2.png",
    },
    {
        title: "Double Chocolate Cookie",
        price: "£2.00",
        category: "Street Food",
        image: "/Double Chocolate.png",
    },

    //Mishti Milkshakes
    {
        title: "Gulap Jam Milkshake",
        price: "£3.50",
        category: "Mishti Milkshakes",
        image: "/Gulap Jam Milkshake.png",
    },
    {
        title: "Kala Jam Milkshake",
        price: "£3.50",
        category: "Mishti Milkshakes",
        image: "/Kala Jam Milkshake.png",
    },
    {
        title: "House Special",
        price: "£4.00",
        desc: "Pistachio & Salted caramel",
        category: "Mishti Milkshakes",
        image: "/House Special1.png",
    },

    //Cold Drink
    {
        title: "Mango Lassi",
        price: "£3.50",
        desc: "House Special",
        category: "Cold Drinks",
        image: "/g13.png",
    },
    {
        title: "Brazilian Lemonade",
        price: "£3.95",
        desc: "House Special",
        category: "Cold Drinks",
        image: "/g4.jpg",
    },
    {
        title: "Strawberry Lemonade",
        price: "£3.95",
        desc: "House Special",
        category: "Cold Drinks",
        image: "/g8.jpg",
    },
    {
        title: "Mango & Passionfruit Twist",
        price: "£3.95",
        desc: "House Special",
        category: "Cold Drinks",
        image: "/Mango & Passionfruit Twist.png",
    },

    //Ice Coffee
    {
        title: "House Ice Coffee",
        price: "£3.95",
        category: "Ice Coffee",
        image: "/g2.jpg",
    },
    {
        title: "Caramel Ice Coffee",
        price: "£3.95",
        category: "Ice Coffee",
        image: "/Caramel Ice Coffee.png",
    },
    {
        title: "Vanilla Ice Coffee",
        price: "£3.95",
        category: "Ice Coffee",
        image: "/Vanilla Ice Coffee.png",
    },
    {
        title: "House Ice Mocha",
        price: "£3.95",
        category: "Ice Coffee",
        image: "/House Ice Mocha.png",
    },
    {
        title: "Ice Matcha Latte",
        price: "£3.95",
        category: "Ice Coffee",
        image: "/Ice Matcha Latte.png",
    },

    //100% Fresh Juice"
    {
        title: "Orange Juice",
        price: "£3.50",
        category: "100% Fresh Juice",
        image: "/Orange Juice.png",
    },
    {
        title: "Pomegranate Juice",
        price: "£3.50",
        category: "100% Fresh Juice",
        image: "/g8.jpg",
    },
    {
        title: "Orange Juice + Ginger Shot",
        price: "£4.50",
        category: "100% Fresh Juice",
        image: "/Orange Juice + Ginger Shot.png",
    },
    {
        title: "Ginger Shot",
        price: "£1.35",
        category: "100% Fresh Juice",
        image: "/Ginger Shot.png",
    },
    {
        title: "Add Fresh Lime",
        price: "£0.65",
        category: "100% Fresh Juice",
        image: "/Lime.png",
    },

    //Tea & Coffee
    {
        title: "Karak Chai",
        price: "£2.00",
        desc: "House Special",
        category: "Tea & Coffee",
        image: "/Karak Chai.png",
    },
    {
        title: "Masala Chai",
        price: "£2.20",
        category: "Tea & Coffee",
        image: "/Masala Chai.png",
    },
    {
        title: "Pink Chai",
        price: "£2.20",
        category: "Tea & Coffee",
        image: "/Pink Chai.jpeg",
    },
    {
        title: "Caramel Chai",
        price: "£2.20",
        category: "Tea & Coffee",
        image: "/last.png",
    },
    {
        title: "Moroccan Tea",
        price: "£2.75",
        category: "Tea & Coffee",
        image: "/Moroccan Tea.png",
    },
    {
        title: "English Tea",
        price: "£1.75",
        category: "Tea & Coffee",
        image: "/english.jpeg",
    },
    {
        title: "Mango Flower Tea",
        price: "£4.19",
        category: "Tea & Coffee",
        image: "/Mango Flower tea.png",
    },
    {
        title: "Karak Coffce",
        price: "£2.00",
        desc: "House Special",
        category: "Tea & Coffee",
        image: "/karak Coffee.png",
    },
    {
        title: "Chai Latte",
        price: "£2.20",
        desc: "House Special",
        category: "Tea & Coffee",
        image: "/Chai Latte.jpeg",
    },
    {
        title: "Espresso",
        price: "£1.50",
        category: "Tea & Coffee",
        image: "/Espresso.png",
    },
    {
        title: "Americano",
        price: "£2.85",
        category: "Tea & Coffee",
        image: "/Americano.png",
    },
    {
        title: "Cappuccino",
        price: "£2.85",
        category: "Tea & Coffee",
        image: "/Cappuccino.png",
    },
    {
        title: "Hot Chocolate",
        price: "£2.00",
        category: "Tea & Coffee",
        image: "/Hot Chocolate.png",
    },
    {
        title: "Double Choc House Mocha",
        price: "£2.40",
        category: "Tea & Coffee",
        image: "/Double Choc House Mocha.png",
    },
];
